CREATE TABLE usuario (
    id_usuario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    email VARCHAR2(150) UNIQUE NOT NULL,
    password_hash VARCHAR2(200) NOT NULL,
    rol VARCHAR2(20) CHECK (rol IN ('ADMIN', 'VENDEDOR')) NOT NULL,
    activo NUMBER(1) DEFAULT 1 CHECK (activo IN (0,1))
);

CREATE TABLE cliente (
    id_cliente NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(120) NOT NULL,
    email VARCHAR2(150),
    telefono VARCHAR2(20),
    direccion VARCHAR2(200)
);

CREATE TABLE producto (
    id_producto NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(120) NOT NULL,
    descripcion VARCHAR2(300),
    precio NUMBER(10,2) CHECK (precio >= 0) NOT NULL,
    stock NUMBER DEFAULT 0 CHECK (stock >= 0),
    activo NUMBER(1) DEFAULT 1 CHECK (activo IN (0,1))
);

CREATE TABLE factura (
    id_factura NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario NUMBER NOT NULL,
    id_cliente NUMBER NOT NULL,
    fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    total NUMBER(12,2) DEFAULT 0 CHECK (total >= 0),

    CONSTRAINT fk_factura_usuario FOREIGN KEY (id_usuario)
        REFERENCES usuario(id_usuario),

    CONSTRAINT fk_factura_cliente FOREIGN KEY (id_cliente)
        REFERENCES cliente(id_cliente)
);

CREATE TABLE detalle_factura (
    id_detalle NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_factura NUMBER NOT NULL,
    id_producto NUMBER NOT NULL,
    cantidad NUMBER CHECK (cantidad > 0) NOT NULL,
    precio_unitario NUMBER(10,2) CHECK (precio_unitario >= 0) NOT NULL,
    subtotal NUMBER(12,2) CHECK (subtotal >= 0) NOT NULL,

    CONSTRAINT fk_detalle_factura FOREIGN KEY (id_factura)
        REFERENCES factura(id_factura),

    CONSTRAINT fk_detalle_producto FOREIGN KEY (id_producto)
        REFERENCES producto(id_producto)
);

CREATE TABLE movimiento_stock (
    id_movimiento NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_producto NUMBER NOT NULL,
    cantidad NUMBER NOT NULL,
    tipo VARCHAR2(20) CHECK (tipo IN ('ENTRADA', 'SALIDA')) NOT NULL,
    fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    descripcion VARCHAR2(200),

    CONSTRAINT fk_mov_producto FOREIGN KEY (id_producto)
        REFERENCES producto(id_producto)
);

